services:
#    nligo_user.example:
#        class: Nligo\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
      nligo_user.manager_user:
          class: Nligo\UserBundle\Manager\UserManager
          arguments:
              em: "@doctrine.orm.entity_manager"
              class: Nligo\UserBundle\Entity\User